### ISSUE TITLE
styled-components is not defined as a peer dependency

### ISSUE THREAD

**Issue by DiFuks** [Wildhoney/ReactShadow#130]
Due to this issue, yarn 2-3 in pnp mode cannot resolve the dependency
<img width="1881" alt="image" src="https://user-images.githubusercontent.com/12777199/158217834-751e7652-1ecd-4e3f-a070-da47bd039990.png">

Workaround: fix with yarn.yml:

```yml
packageExtensions:
  react-shadow@*:
    peerDependencies:
      styled-components: ^5.3.0
```
