### ISSUE TITLE
Trouble Loading Custom Font Into Shadow DOM in my Chrome Extension

### ISSUE THREAD

**Issue by lancesnider** [Wildhoney/ReactShadow#139]
I'm having trouble loading my custom font into my Chrome Extension. 

```js
// index.js
<root.div>
  <style dangerouslySetInnerHTML={{ __html: stylesheet }} />
  <App />
</root.div>
```

```scss
@font-face {
    font-family: 'defaultText';
    src: url('chrome-extension://' + $extensionId + '/Inter-Regular.woff2')
        format('woff2'),
      url('chrome-extension://' + $extensionId + '/Inter-Regular.woff')
        format('woff');
  }

.some-class {
  // I set the fallback font to serif so it's easy to catch
  font-family: 'defaultText', serif;
}
```
Here's the `style` tag that gets put inside my shadow. I've tested those `urls` and the font is there.

![Screen Shot 2022-08-31 at 11 47 57 AM](https://user-images.githubusercontent.com/3202211/187759429-d369ed28-54b0-4480-849b-9a772245d470.png)

If I change `<root.div> ` to `<div>` the fonts load properly.

Thanks!
